[theme]
primaryColor = "#005BAC"         # USGA blue
backgroundColor = "#ffffff"      # clean white
secondaryBackgroundColor = "#f0f2f6"  # light gray for card contrast
textColor = "#002664"            # USGA navy blue
font = "sans serif"
