[theme]
primaryColor = "#005BAC"         # USGA blue
backgroundColor = "#ffffff"      # clean white
secondaryBackgroundColor = "#f0f2f6"  # light gray for card contrast
textColor = "#002664"            # USGA navy blue
font = "sans serif"

[server]
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[client]
showSidebarNavigation = false

[ui]
favicon = "https://idss-proxy.imgix.net/https%3A%2F%2Ffiles.idss.com%2FC32%2F0efcbc6c-d7cc-4aa2-9ee5-ca7e854a3fe3.png?auto=compress%2Cformat&fit=max&h=1080&q=80&w=1920&s=25f63e35e4c282d2d2a004f9827045c7"
